name: monekin
description: The best personal finance controller on the market. Learn to save and manage your finances with Monekin.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

publish_to: 'none'

# [VersionName]+[VersionNumber] -> The version number follow the below convetion:
#
# XXXXX.YY.ZZZ
#
# The X represents the major releases, and can be up to infinity. Never start by a zero
# The Y represents the minor releases, and can be up to 99. Always start by a zero
# The Z represents the patch releases, and can be up to 999. Always start by a zero
version: 5.0.3+500003

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # General
  cupertino_icons: ^1.0.6
  collection: ^1.18.0
  equatable: ^2.0.5
  path: ^1.9.0
  async: ^2.11.0
  rxdart: ^0.27.7
  google_mobile_ads: ^4.0.0

  # i18n
  intl: ^0.18.1
  slang: any
  slang_flutter: any

  # Drift
  drift: ^2.16.0
  path_provider: ^2.1.2
  http: any
  sqlite3: ^2.4.0
  sqlite3_flutter_libs: ^0.5.20

  # Other
  flutter_svg: ^2.0.10+1
  permission_handler: ^11.3.0
  json_annotation: ^4.8.1
  fl_chart: ^0.66.2
  file_picker: ^6.2.0
  share_plus: ^7.2.2
  url_launcher: ^6.2.5
  uuid: ^4.3.3
  csv: any
  dotted_border: ^2.1.0
  package_info_plus: any
  introduction_screen: ^3.1.12
  dynamic_color: ^1.7.0
  copy_with_extension: ^5.0.4
  freezed_annotation: ^2.4.1
  in_app_purchase: ^3.1.13
  auto_route: ^7.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  # Generators:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1 # Package to regenerate icons (config later in this file). To run, type `dart run flutter_launcher_icons`
  drift_dev: ^2.16.0
  slang_build_runner: ^3.30.0 # To regenerate the translations run 'dart run slang'
  copy_with_extension_gen: ^5.0.4
  freezed: ^2.4.7
  auto_route_generator: ^7.3.2

flutter_launcher_icons:
  image_path: 'assets/resources/appIcon-removebg.png'
  android: true
  ios: false
  windows:
    generate: true
  macos:
    generate: false

flutter:
  uses-material-design: true

  assets:
    - assets/resources/
    - assets/icons/app_onboarding/
    - assets/icons/avatars/
    - assets/icons/currency_flags/
    - assets/icons/page_states/
    - assets/icons/supported_selectable_icons/entertainment/
    - assets/icons/supported_selectable_icons/other/
    - assets/icons/supported_selectable_icons/money/
    - assets/icons/supported_selectable_icons/food/
    - assets/icons/supported_selectable_icons/medical/
    - assets/icons/supported_selectable_icons/transport/
    - assets/icons/supported_selectable_icons/technology/
    - assets/icons/supported_selectable_icons/logos/financial_institutions/
    - assets/sql/
    - assets/sql/migrations/
    - assets/icons/backup/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito/Nunito-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito/Nunito-ExtraLightItalic.ttf
          style: italic
          weight: 200
